// <auto-generated />
using System;
using Mapper.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mapper.Data.Migrations
{
    [DbContext(typeof(MapperContext))]
    partial class MapperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mapper.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfil");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee41c173-2df4-4014-ab9f-93ed74579fc7"),
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("Mapper.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09ed19f5-a91c-424a-aff0-d2f0e63b8a26"),
                            IdPerfil = new Guid("ee41c173-2df4-4014-ab9f-93ed74579fc7"),
                            Nome = "Snoopy"
                        },
                        new
                        {
                            Id = new Guid("911417ce-88f7-48c5-8186-4695b60a92d8"),
                            IdPerfil = new Guid("ee41c173-2df4-4014-ab9f-93ed74579fc7"),
                            Nome = "Lola"
                        },
                        new
                        {
                            Id = new Guid("d5318abd-2b47-4115-a900-4c6fb1792456"),
                            IdPerfil = new Guid("ee41c173-2df4-4014-ab9f-93ed74579fc7"),
                            Nome = "Tobias"
                        });
                });

            modelBuilder.Entity("Mapper.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Mapper.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
