// <auto-generated />
using System;
using Mapper.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mapper.Api.Migrations
{
    [DbContext(typeof(MapperContext))]
    [Migration("20200823174357_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mapper.Api.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02f4b241-a1ad-488f-b04b-0bc7cbf7f382"),
                            Nome = "Tobias"
                        });
                });

            modelBuilder.Entity("Mapper.Api.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfil");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5777322-6c48-4482-8194-95e15fbe4a74"),
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("Mapper.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1c923c4-bdb6-4c1b-9e02-acb845b3ab5a"),
                            IdPerfil = new Guid("e5777322-6c48-4482-8194-95e15fbe4a74"),
                            Nome = "Snoopy"
                        },
                        new
                        {
                            Id = new Guid("b5a09339-6f6d-4a9b-9b81-17fa1a16cdb3"),
                            IdPerfil = new Guid("e5777322-6c48-4482-8194-95e15fbe4a74"),
                            Nome = "Lola"
                        },
                        new
                        {
                            Id = new Guid("1f47bfdc-19ec-4dc2-bd8f-3dc3cccbe185"),
                            IdPerfil = new Guid("e5777322-6c48-4482-8194-95e15fbe4a74"),
                            Nome = "Tobias"
                        });
                });

            modelBuilder.Entity("Mapper.Api.Entities.Usuario", b =>
                {
                    b.HasOne("Mapper.Api.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
