// <auto-generated />
using System;
using Mapper.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mapper.Api.Migrations
{
    [DbContext(typeof(MapperContext))]
    partial class MapperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mapper.Api.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfil");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09133751-e1b5-45f4-9cdc-2881b362ec0f"),
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("Mapper.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f45917e-0391-42bc-a677-c3666d18ab82"),
                            IdPerfil = new Guid("09133751-e1b5-45f4-9cdc-2881b362ec0f"),
                            Nome = "Snoopy"
                        },
                        new
                        {
                            Id = new Guid("2ab71627-e14c-48ee-ae7e-ac411b8fdf8b"),
                            IdPerfil = new Guid("09133751-e1b5-45f4-9cdc-2881b362ec0f"),
                            Nome = "Lola"
                        },
                        new
                        {
                            Id = new Guid("1bb7f3b7-735d-4455-9d29-96c87473ac1a"),
                            IdPerfil = new Guid("09133751-e1b5-45f4-9cdc-2881b362ec0f"),
                            Nome = "Tobias"
                        });
                });

            modelBuilder.Entity("Mapper.Api.Entities.Usuario", b =>
                {
                    b.HasOne("Mapper.Api.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
